import { Menu } from './menu.model';

export const menuItems = [
    new Menu(10, 'Inicio', '/admin', null, 'dashboard', null, false, 0),
    new Menu(20, 'Perfil', null, null, 'person', null, true, 0),
    new Menu(21, 'Mis datos', '/admin/account/information', null, 'info', null, false, 20),
    new Menu(22, 'Mis direcciones', '/admin/account/addresses', null, 'location_pin', null, false, 20),
    new Menu(23, 'Mis compras', '/admin/account/orders', null, 'store', null, false, 20),
    new Menu(30, 'Administración', null, null, 'admin_panel_settings', null, true, 0),
    new Menu(31, 'Banners', '/admin/banners', null, 'add_circle_outline', null, false, 30),
    new Menu(32, 'Vendedores', '/admin/customers', null, 'people', null, false, 30),
    new Menu(33, 'Clientes', '/admin/users', null, 'group_add', null, false, 30),
    new Menu(34, 'Categorías', '/admin/products/categories', null, 'category', null, false, 30),
    new Menu(35, 'FAQs', '/admin/faqs', null, 'question_answer', null, false, 30),
    new Menu(36, 'Paquetes de anuncios', '/admin/ads', null, 'announcement', null, false, 30),
    new Menu(37, 'Productos', '/admin/products/all', null, 'shopping_cart', null, false, 30),
    new Menu(38, 'Anuncios', '/admin/advertisements/all', null, 'announcement', null, false, 30),
    //new Menu(25, 'Notificaciones', '/admin/customers', null, 'notifications', null, false, 20),

    //new Menu(23, 'Detalle de producto', '/admin/products/product-detail', null, 'remove_red_eye', null, false, 20),
    new Menu(40, 'Productos', null, null, 'shopping_cart', null, true, 0),
    new Menu(41, 'Mis productos', '/admin/products/product-list', null, 'list', null, false, 40),
    new Menu(42, 'Publicar producto', '/admin/products/add-product', null, 'add_circle', null, false, 40),
    new Menu(43, 'Pedidos', '/admin/sales', null, 'shopping_bag', null, false, 40),
    //new Menu(50, 'Perfil', '/admin/verify', null, 'person', null, false, 0),
    new Menu(60, 'Anuncios clasificados', null, null, 'announcement', null, true, 0),
    new Menu(61, 'Mis anuncios', '/admin/advertisements/advertisement-list', null, 'list', null, false, 60),
    new Menu(61, 'Mis paquetes', '/admin/advertisements/bundle-list', null, 'photo_library', null, false, 60),
    new Menu(63, 'Paquetes', '/admin/advertisements/ad-bundle', null, 'account_balance_wallet', null, false, 60),
    new Menu(64, 'Publicar anuncio', '/admin/advertisements/add-advertisement', null, 'add_circle', null, false, 60),
    new Menu(70, 'Verificar', '/admin/verify', null, 'verified_user', null, false, 0),
    //new Menu(32, 'Transactions', '/admin/sales/transactions', null, 'local_atm', null, false, 30),
    new Menu(80, 'Ir a la tienda', '/', null, 'store', null, false, 0),
    //new Menu(60, 'Coupons', '/admin/coupons', null, 'card_giftcard', null, false, 0),
    //new Menu(70, 'Withdrawal', '/admin/withdrawal', null, 'credit_card', null, false, 0),
    //new Menu(80, 'Analytics', '/admin/analytics', null, 'multiline_chart', null, false, 0),
    //new Menu(90, 'Refund', '/admin/refund', null, 'restore', null, false, 0),
    //new Menu(100, 'Followers', '/admin/followers', null, 'follow_the_signs', null, false, 0),
    //new Menu(110, 'Support', '/admin/support', null, 'support', null, false, 0),
    //new Menu(120, 'Reviews', '/admin/reviews', null, 'insert_comment', null, false, 0),
    //new Menu(140, 'Level 1', null, null, 'more_horiz', null, true, 0),
    //new Menu(141, 'Level 2', null, null, 'folder_open', null, true, 140),
    //new Menu(142, 'Level 3', null, null, 'folder_open', null, true, 141),
    //new Menu(143, 'Level 4', null, null, 'folder_open', null, true, 142),
    //new Menu(144, 'Level 5', null, 'http://themeseason.com', 'link', null, false, 143),
    //new Menu(200, 'External Link', null, 'http://themeseason.com', 'open_in_new', '_blank', false, 0)
]